### ISSUE TITLE
Run ROS Stereo-Inertial with recorded .bag from realsense D435i

### ISSUE THREAD

**Issue by Styazoua** [thien94/orb_slam_3_ros#29]
Hello,

First I want to say that I am not that deep into ROS.
I would like to run Stereo-Inertial with ROS and a pre recorded bag file with Intel RealSense D435i.
I already tried the ros_stereo_inertial example.
But while looking into the source code I have seen that it subscribes to /imu topic.
But when I record with the D435i I have the IMU data devided in 2 separate topics (acceleration and gyro).
Is there a way to run that without modifying the whole example?
I was hoping to find something in this repo.

**Comment by IamRam3** [comment]
Hi @Styazoua you can record rosbag after setting "unite_imu_method" as 1 or 2 
Then I think you can be able to run.

**Comment by Filippo-Steffenel** [comment]
Hi @Styazoua  I have the same problem, do you find a solution?

**Comment by Styazoua** [comment]
Yes the "unite_imu_method" argument solved the problem.
I use this command to launch the camera and record:
```
# launch camera
roslaunch realsense2_camera rs_camera.launch enable_accel:=true enable_gyro:=true enable_infra1:=true enable_infra2:=true unite_imu_method:=linear_interpolation infra_width:=640 infra_height:=480 global_time_enable:=true

# rosbag record
rosbag record -O recording.bag /camera/imu /camera/infra1/image_rect_raw /camera/infra2/image_rect_raw
```
Imu data is published on "/camera/imu" topic
