### ISSUE TITLE
No rule to make target (libg2o.so), Failed to build orb_slam3_ros

### ISSUE THREAD

**Issue by lazuraihan** [thien94/orb_slam_3_ros#32]
I need help..
When i tried to build of the orb_slam3_ros through _catkin build_, it appeared failed to build the package due to the libg2o.so file that was missing.
Is there any solution to fix this??
![libg2o failed](https://github.com/thien94/orb_slam3_ros/assets/105598568/3ff80342-de93-4a01-9b04-23c67da0c1bf)

I'm using NVIDIA Jetson Nano, with ubuntu 18 and melodic ROS version

Thank you

**Comment by Taoran2023** [comment]
hey how did you solved this, I meet same problem.
